import{S as w,i as u,a as L}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S=document.querySelector(".form"),p=document.querySelector(".gallery"),y=document.querySelector(".loader"),n=document.querySelector('button[data-action="load-more"]'),q=document.querySelector(".search-input");y.style.display="none";let l=1;const m=40;let c="";const v=new w(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});async function d(o){c=o;const t={key:"41712066-bd7b5e249df7a86bd45ef70ea",q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:m},s=new URLSearchParams(t);try{return(await L.get(`https://pixabay.com/api/?${s}`)).data}catch(a){console.error(a),u.error({position:"topRight",width:"10px",message:"Sorry, there are no images matching your search query. Please try again"})}finally{y.style.display="none"}}function f(o){if(o.hits.length>0){const t=o.hits.reduce((s,{webformatURL:a,largeImageURL:e,tags:r,likes:i,views:g,comments:h,downloads:b})=>s+`<li class="gallery-item">
          <a class="gallery-link" href="${e}">
           <img class="gallery-image"
           src="${a}"
           alt="${r}"
           />
          </a>
          <div class="description">
          <p><b>Likes</b>${i}</p>
          <p><b>Views</b>${g}</p>
          <p><b>Comments</b>${h}</p>
          <p><b>Downloads</b>${b}</p>
          </div>
        </li>`,"");p.insertAdjacentHTML("beforeend",t),v.refresh()}else n.style.display="none",u.error({position:"topRight",width:"10px",message:"Sorry, there are no images matching your search query. Please try again"})}S.addEventListener("submit",async o=>{o.preventDefault(),n.style.display="none",p.innerHTML="",y.style.display="block",l=1;const t=q.value.trim(),s=await d(t);f(s),s>0&&(n.style.display="block"),o.target.reset()});const R=()=>{const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};n.addEventListener("click",async()=>{n.style.display="none";const{totalHits:o}=await d(c);if(y.style.display="block",l*m>=o)u.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});else{l+=1;const t=await d(c);f(t),n.style.display="block",R()}});
//# sourceMappingURL=commonHelpers.js.map
